//up to patch 2.2
const characters = [
    {
        name: "Amber",
        weapon: "Bow",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/75/Amber_Icon.png/revision/latest?cb=20210213161233"
    },
    {
        name: "Barbara",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/6a/Barbara_Icon.png/revision/latest?cb=20230302072845",
    },
    {
        name: "Beidou",
        weapon: "Claymore",
        element: "Electro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e1/Beidou_Icon.png/revision/latest?cb=20210214011821",
    },
    {
        name: "Bennett",
        weapon: "Sword",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/79/Bennett_Icon.png/revision/latest?cb=20210214011829",
    },
    {
        name: "Chongyun",
        weapon: "Claymore",
        element: "Cryo",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/35/Chongyun_Icon.png/revision/latest?cb=20210213163430",
    },
    {
        name: "Diluc",
        weapon: "Claymore",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/3d/Diluc_Icon.png/revision/latest?cb=20210213163824",
    },
    {
        name: "Fischl",
        weapon: "Bow",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9a/Fischl_Icon.png/revision/latest?cb=20220627171007",
    },
    {
        name: "Jean",
        weapon: "Sword",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/64/Jean_Icon.png/revision/latest?cb=20220602180528",
    },
    {
        name: "Kaeya",
        weapon: "Sword",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b6/Kaeya_Icon.png/revision/latest?cb=20210214011902",
    },
    {
        name: "Keqing",
        weapon: "Sword",
        element: "Electro",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/52/Keqing_Icon.png/revision/latest?cb=20210213162751",
    },
    {
        name: "Lisa",
        weapon: "Catalyst",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/65/Lisa_Icon.png/revision/latest?cb=20210213163538",
    },
    {
        name: "Mona",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/41/Mona_Icon.png/revision/latest?cb=20220601033558",
    },
    {
        name: "Ningguang",
        weapon: "Catalyst",
        element: "Geo",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e0/Ningguang_Icon.png/revision/latest?cb=20220210040239",
    },
    {
        name: "Noelle",
        weapon: "Claymore",
        element: "Geo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/8/8e/Noelle_Icon.png/revision/latest?cb=20210214011929",
    },
    {
        name: "Qiqi",
        weapon: "Sword",
        element: "Cryo",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b3/Qiqi_Icon.png/revision/latest?cb=20220316020612",
    },
    {
        name: "Razor",
        weapon: "Claymore",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b8/Razor_Icon.png/revision/latest?cb=20210214011936",
    },
    {
        name: "Sucrose",
        weapon: "Catalyst",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/0e/Sucrose_Icon.png/revision/latest?cb=20210213163209",
    },
    {
        name: "Venti",
        weapon: "Bow",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/f1/Venti_Icon.png/revision/latest?cb=20210214011949",
    },
    {
        name: "Xiangling",
        weapon: "Polearm",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/39/Xiangling_Icon.png/revision/latest?cb=20210214011301",
    },
    {
        name: "Xingqiu",
        weapon: "Sword",
        element: "Hydro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d4/Xingqiu_Icon.png/revision/latest?cb=20210214012057",
    },
    {
        name: "Klee",
        weapon: "Catalyst",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9c/Klee_Icon.png/revision/latest?cb=20210214011911",
    },
    {
        name: "Diona",
        weapon: "Bow",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/40/Diona_Icon.png/revision/latest?cb=20220210035554",
    },
    {
        name: "Tartaglia",
        weapon: "Bow",
        element: "Hydro",
        region: "Snezhnaya",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/8/85/Tartaglia_Icon.png/revision/latest?cb=20210213163935",
    },
    {
        name: "Xinyan",
        weapon: "Claymore",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/24/Xinyan_Icon.png/revision/latest?cb=20210213163013",
    },
    {
        name: "Zhongli",
        weapon: "Polearm",
        element: "Geo",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/a/a6/Zhongli_Icon.png/revision/latest?cb=20210213163026",
    },
    {
        name: "Albedo",
        weapon: "Sword",
        element: "Geo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/30/Albedo_Icon.png/revision/latest?cb=20210213163457",
    },
    {
        name: "Ganyu",
        weapon: "Bow",
        element: "Cryo",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/79/Ganyu_Icon.png/revision/latest?cb=20230519012425",
    },
    {
        name: "Xiao",
        weapon: "Polearm",
        element: "Anemo",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/fd/Xiao_Icon.png/revision/latest?cb=20210214012045",
    },
    {
        name: "Hutao",
        weapon: "Polearm",
        element: "Pyro",
        region: "Liyue",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e9/Hu_Tao_Icon.png/revision/latest?cb=20210228210611",
    },
    {
        name: "Rosaria",
        weapon: "Polearm",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/35/Rosaria_Icon.png/revision/latest?cb=20220601032845",
    },
    {
        name: "Yanfei",
        weapon: "Catalyst",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/54/Yanfei_Icon.png/revision/latest?cb=20210422063525",
    }, {
        name: "Eula",
        weapon: "Claymore",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/a/af/Eula_Icon.png/revision/latest?cb=20210511040616",
    },
    {
        name: "Kaedehara Kazuha",
        weapon: "Sword",
        element: "Anemo",
        region: "Inazuma",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e3/Kaedehara_Kazuha_Icon.png/revision/latest?cb=20210623063513",
    },
    {
        name: "Kamisato Ayaka",
        weapon: "Sword",
        element: "Cryo",
        region: "Inazuma",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/51/Kamisato_Ayaka_Icon.png/revision/latest?cb=20211221231648",
    }, {
        name: "Sayu",
        weapon: "Claymore",
        element: "Anemo",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/22/Sayu_Icon.png/revision/latest?cb=20210810101044",
    },{
        name: "Yoimiya",
        weapon: "Bow",
        element: "Pyro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/8/88/Yoimiya_Icon.png/revision/latest?cb=20220214235604",
    },
    {
        name: "Kujou Sara",
        weapon: "Bow",
        element: "Electro",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/df/Kujou_Sara_Icon.png/revision/latest?cb=20220210040844",
    }, {
        name: "Raiden Shogun",
        weapon: "Polearm",
        element: "Electro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/24/Raiden_Shogun_Icon.png/revision/latest?cb=20220316020439",
    },{
        name: "Sangonomiya Kokomi",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/ff/Sangonomiya_Kokomi_Icon.png/revision/latest?cb=20210921103819",
    },
    {
        name: "Thoma",
        weapon: "Polearm",
        element: "Pyro",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/5b/Thoma_Icon.png/revision/latest?cb=20211014011046",
    }, 
]

export {characters};