//up to patch 2.2
const characters = [
    {
        name: "Amber",
        weapon: "Bow",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./amber.webp"
    },
    {
        name: "Barbara",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./barbara.webp",
    },
    {
        name: "Beidou",
        weapon: "Claymore",
        element: "Electro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./beidou.webp",
    },
    {
        name: "Bennett",
        weapon: "Sword",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./bennett.webp",
    },
    {
        name: "Chongyun",
        weapon: "Claymore",
        element: "Cryo",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./chongyun.webp",
    },
    {
        name: "Diluc",
        weapon: "Claymore",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./diluc.webp",
    },
    {
        name: "Fischl",
        weapon: "Bow",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./fischl.webp",
    },
    {
        name: "Jean",
        weapon: "Sword",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./jean.webp",
    },
    {
        name: "Kaeya",
        weapon: "Sword",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./kaeya.webp",
    },
    {
        name: "Keqing",
        weapon: "Sword",
        element: "Electro",
        region: "Liyue",
        rarity: "5 star",
        icon: "./keqing.webp",
    },
    {
        name: "Lisa",
        weapon: "Catalyst",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./lisa.webp",
    },
    {
        name: "Mona",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./mona.webp",
    },
    {
        name: "Ningguang",
        weapon: "Catalyst",
        element: "Geo",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./ningguang.webp",
    },
    {
        name: "Noelle",
        weapon: "Claymore",
        element: "Geo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./noelle.webp",
    },
    {
        name: "Qiqi",
        weapon: "Sword",
        element: "Cryo",
        region: "Liyue",
        rarity: "5 star",
        icon: "./qiqi.webp",
    },
    {
        name: "Razor",
        weapon: "Claymore",
        element: "Electro",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./razor.webp",
    },
    {
        name: "Sucrose",
        weapon: "Catalyst",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./sucrose.webp",
    },
    {
        name: "Venti",
        weapon: "Bow",
        element: "Anemo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./venti.webp",
    },
    {
        name: "Xiangling",
        weapon: "Polearm",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./xiangling.webp",
    },
    {
        name: "Xingqiu",
        weapon: "Sword",
        element: "Hydro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./xingqiu.webp",
    },
    {
        name: "Klee",
        weapon: "Catalyst",
        element: "Pyro",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./klee.webp",
    },
    {
        name: "Diona",
        weapon: "Bow",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./diona.webp",
    },
    {
        name: "Tartaglia",
        weapon: "Bow",
        element: "Hydro",
        region: "Snezhnaya",
        rarity: "5 star",
        icon: "./childe.webp",
    },
    {
        name: "Xinyan",
        weapon: "Claymore",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./xinyan.webp",
    },
    {
        name: "Zhongli",
        weapon: "Polearm",
        element: "Geo",
        region: "Liyue",
        rarity: "5 star",
        icon: "./zhongli.webp",
    },
    {
        name: "Albedo",
        weapon: "Sword",
        element: "Geo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./albedo.webp",
    },
    {
        name: "Ganyu",
        weapon: "Bow",
        element: "Cryo",
        region: "Liyue",
        rarity: "5 star",
        icon: "./ganyu.webp",
    },
    {
        name: "Xiao",
        weapon: "Polearm",
        element: "Anemo",
        region: "Liyue",
        rarity: "5 star",
        icon: "./xiao.webp",
    },
    {
        name: "Hutao",
        weapon: "Polearm",
        element: "Pyro",
        region: "Liyue",
        rarity: "5 star",
        icon: "./hutao.webp",
    },
    {
        name: "Rosaria",
        weapon: "Polearm",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "4 Star",
        icon: "./rosaria.webp",
    },
    {
        name: "Yanfei",
        weapon: "Catalyst",
        element: "Pyro",
        region: "Liyue",
        rarity: "4 Star",
        icon: "./yanfei.webp",
    }, {
        name: "Eula",
        weapon: "Claymore",
        element: "Cryo",
        region: "Mondstadt",
        rarity: "5 star",
        icon: "./eul.webp",
    },
    {
        name: "Kaedehara Kazuha",
        weapon: "Sword",
        element: "Anemo",
        region: "Inazuma",
        rarity: "5 star",
        icon: "./kazuha.webp",
    },
    {
        name: "Kamisato Ayaka",
        weapon: "Sword",
        element: "Cryo",
        region: "Inazuma",
        rarity: "5 star",
        icon: "./ayaka.webp",
    }, {
        name: "Sayu",
        weapon: "Claymore",
        element: "Anemo",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "./sayu.webp",
    },{
        name: "Yoimiya",
        weapon: "Bow",
        element: "Pyro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "./yoimiya.webp",
    },
    {
        name: "Kujou Sara",
        weapon: "Bow",
        element: "Electro",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "./sara.webp",
    }, {
        name: "Raiden Shogun",
        weapon: "Polearm",
        element: "Electro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "./raiden.webp",
    },{
        name: "Sangonomiya Kokomi",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Inazuma",
        rarity: "5 star",
        icon: "./kokomi.webp",
    },
    {
        name: "Thoma",
        weapon: "Polearm",
        element: "Pyro",
        region: "Inazuma",
        rarity: "4 Star",
        icon: "./thoma.webp",
    }, 
]

export {characters};